global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'json-exporter'
    static_configs:
      - targets: ['json-exporter:7979']

  - job_name: 'easyrent-system-metrics-json'
    metrics_path: /probe
    params:
      module: [easyrent_system_metrics]
    static_configs:
      - targets:
          - http://host.docker.internal:8000/v1/system/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979
